train:
  approach: "transformer"          # transformer | baseline
  model_name: "distilbert-base-uncased"
  batch_size: 16
  epochs: 1
  learning_rate: 2e-5
  max_length: 128
  validation_split: 0.2

data:
  dataset_name: "imdb"
  raw_dir: "data/raw"
  train_file: "imdb_train.parquet"
  test_file: "imdb_test.parquet"

mlflow:
  experiment_name: "sentiment-analysis"

